import { useState, useCallback } from 'react';
import {
  LiveKitRoom,
  RoomAudioRenderer,
  ControlBar,
  useDataChannel,
  useConnectionState,
} from '@livekit/components-react';
import '@livekit/components-styles';
import { AlertTriangle, CheckCircle2, MessageSquare } from 'lucide-react';

export default function App() {
  const [token, setToken] = useState("");
  const [serverUrl, setServerUrl] = useState("wss://aegis-e8u2c410.livekit.cloud");
  const [connected, setConnected] = useState(false);

  if (!connected) {
    return (
      <div style={{ padding: '2rem', maxWidth: '600px', margin: '0 auto', fontFamily: 'sans-serif' }}>
        <h1 style={{ fontSize: '1.5rem', marginBottom: '1rem' }}>Scam Detection Agent</h1>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
          <div>
            <label style={{ display: 'block', marginBottom: '0.5rem' }}>LiveKit Server URL</label>
            <input 
              type="text" 
              value={serverUrl} 
              onChange={e => setServerUrl(e.target.value)} 
              style={{ width: '100%', padding: '0.5rem', borderRadius: '4px', border: '1px solid #ccc' }} 
            />
          </div>
          <div>
            <label style={{ display: 'block', marginBottom: '0.5rem' }}>LiveKit Auth Token</label>
            <textarea 
              value={token} 
              onChange={e => setToken(e.target.value)} 
              rows={4}
              placeholder={"Paste the token generated by get_token.py here..."}
              style={{ width: '100%', padding: '0.5rem', borderRadius: '4px', border: '1px solid #ccc' }} 
            />
          </div>
          <button 
            onClick={() => setConnected(true)}
            disabled={!token}
            style={{ 
              padding: '0.75rem 1.5rem', 
              backgroundColor: '#2563eb', 
              color: 'white', 
              border: 'none', 
              borderRadius: '6px', 
              cursor: 'pointer',
              fontWeight: 'bold'
            }}
          >
            Connect to Room
          </button>
        </div>
      </div>
    );
  }

  return (
    <LiveKitRoom
      video={false}
      audio={true}
      token={token}
      serverUrl={serverUrl}
      connect={true}
      style={{ height: '100vh', display: 'flex', flexDirection: 'column' }}
    >
      <div style={{ flex: 1, position: 'relative' }}>
         <ScamAlertDisplay />
      </div>
      <RoomAudioRenderer />
      {/* Provide controls so the user can unmute themselves */}
      <ControlBar variation="minimal" controls={{ microphone: true, camera: false, screenShare: false }} />
    </LiveKitRoom>
  );
}

function ScamAlertDisplay() {
  const connectionState = useConnectionState();
  const [latestAlert, setLatestAlert] = useState<{status: string, reason: string, probability: number} | null>(null);
  const [transcription, setTranscription] = useState<{text: string, isFinal: boolean}>({text: "", isFinal: true});

  useDataChannel("ai_events", useCallback((msg: any) => {
    try {
      const decoder = new TextDecoder();
      const payload = decoder.decode(msg.payload);
      const data = JSON.parse(payload);
      
      console.log("Received data:", data);
      
      if (data.type === "scam_alert") {
        setLatestAlert({
          status: data.status,
          reason: data.reason,
          probability: data.probability
        });
        
        if (data.status === "safe") {
            setTimeout(() => {
                setLatestAlert(current => current?.status === "safe" ? null : current);
            }, 8000);
        }
      } else if (data.type === "transcription") {
        setTranscription({ text: data.text, isFinal: data.is_final });
      }
    } catch (e) {
      console.error("Error decoding message:", e);
    }
  }, []));

  return (
    <div style={{ 
      padding: '2rem', 
      maxWidth: '800px', 
      margin: '0 auto', 
      fontFamily: 'sans-serif',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      paddingTop: '2rem'
    }}>
      <h2 style={{ marginBottom: '2rem', color: 'white' }}>Agent Status: {connectionState}</h2>
      
      {transcription.text && (
        <div style={{
          backgroundColor: '#1f2937',
          color: '#f3f4f6',
          padding: '1rem 2rem',
          borderRadius: '12px',
          marginBottom: '2rem',
          width: '100%',
          display: 'flex',
          alignItems: 'center',
          gap: '1rem',
          opacity: transcription.isFinal ? 1 : 0.7,
        }}>
          <MessageSquare size={32} color="#9ca3af" />
          <p style={{ fontSize: '1.25rem', margin: 0 }}>
            {transcription.text}
            {!transcription.isFinal && <span style={{ opacity: 0.5 }}>...</span>}
          </p>
        </div>
      )}

      {latestAlert ? (
        <div style={{
          backgroundColor: latestAlert.status === 'danger' ? '#fef2f2' : '#f0fdf4',
          border: `2px solid ${latestAlert.status === 'danger' ? '#ef4444' : '#22c55e'}`,
          borderRadius: '12px',
          padding: '2rem',
          width: '100%',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          gap: '1rem',
          boxShadow: '0 10px 15px -3px rgb(0 0 0 / 0.1)'
        }}>
          {latestAlert.status === 'danger' ? 
            <AlertTriangle size={64} color="#ef4444" /> : 
            <CheckCircle2 size={64} color="#22c55e" />
          }
          
          <h3 style={{ 
            fontSize: '1.5rem', 
            margin: 0, 
            color: latestAlert.status === 'danger' ? '#991b1b' : '#166534' 
          }}>
            {latestAlert.status === 'danger' ? 'SCAM RISK DETECTED' : 'Conversation Seems Safe'}
          </h3>
          
          <p style={{ fontSize: '1.25rem', textAlign: 'center', margin: 0 }}>
            {latestAlert.reason}
          </p>
          
          <div style={{
            backgroundColor: latestAlert.status === 'danger' ? '#fee2e2' : '#dcfce7',
            padding: '0.5rem 1rem',
            borderRadius: '999px',
            fontWeight: 'bold',
            color: latestAlert.status === 'danger' ? '#b91c1c' : '#15803d'
          }}>
            Probability: {(latestAlert.probability * 100).toFixed(1)}%
          </div>
        </div>
      ) : (
        <div style={{ color: '#9ca3af', fontSize: '1.25rem' }}>
          Waiting for speech analysis... Speak into your microphone.
        </div>
      )}
    </div>
  );
}
